name: microngo_angular
description: A web app that uses AngularDart Components
version: 0.0.1
#homepage: https://www.example.com
#author: S.-C. Lee <email@example.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_router: any
  angular_components: ^0.13.0
  angular_forms: any
  http: any
  phoenix:
    git: "https://github.com/sclee15/phoenix_channel.git"

dev_dependencies:
  angular_test: any
  build_runner: any
  build_test: any
  build_web_compilers: any
  pedantic: any
  test: any
  sass_builder: any